export const LATEST_NEWS_REQUEST = 'LATEST_NEWS_REQUEST';
export const LATEST_NEWS_SUCCESS = 'LATEST_NEWS_SUCCESS';
export const LATEST_NEWS_FAILURE = 'LATEST_NEWS_FAILURE';

export const HOTEST_NEWS_REQUEST = 'HOTEST_NEWS_REQUEST';
export const HOTEST_NEWS_SUCCESS = 'HOTEST_NEWS_SUCCESS';
export const HOTEST_NEWS_FAILURE = 'HOTEST_NEWS_FAILURE';

export const SECTIONS_REQUEST = 'SECTIONS_REQUEST';
export const SECTIONS_SUCCESS = 'SECTIONS_SUCCESS';
export const SECTIONS_FAILURE = 'SECTIONS_FAILURE';

export const SECTION_REQUEST = 'SECTION_REQUEST';
export const SECTION_SUCCESS = 'SECTION_SUCCESS';
export const SECTION_FAILURE = 'SECTION_FAILURE';

export const CHANGE_SCREEN = 'CHANGE_SCREEN';
export const CHANGE_SECTION = 'CHANGE_SECTION';